### ISSUE TITLE
Animated GIF showing evolution of the board

### ISSUE THREAD

**Issue by anishkny** [xiegeo/commit-sudoku#45]
Hey @xiegeo 

This idea has been kicking around in my head for a while. Would be cool to create a GIF ([something like this](http://commit-sudoku.surge.sh/output.gif)) that shows evolution of the board from start to current state. 

I have a [PR](https://github.com/anishkny/commit-sudoku/pull/1) in my fork that does the following:

1. Get list of commits using `git log`
1. Get state of table at each commit using `git show $SHA:README.md`
1. Render each state in [Puppeteer](https://github.com/GoogleChrome/puppeteer) to PNG
1. Encode GIF from rendered PNGs

Its set to work on Travis. 

Thoughts?

**Comment by xiegeo** [comment]
That looks so cool. I think we can add a section above testing in the readme to show it.

I assume there is a way to set it up such that only CI for the master branch will update the online image.

There is some flashing of numbers, it's from simultaneous pull requests. Can we just follow only the main branch and ignore the branched commits? I am not too sure on this since the flashing artifact is also interesting.

Can you add instructions for running animation/index.js locally? Including the required programs and supported operating systems? I think this instruction should go into something like an animation/readme.md file.

Whenever you are ready, please submit this PR.

**Comment by anishkny** [comment]
Sounds good. Will make those changes and send out PR!
